googlemaps/fleet-debugger

src/App.js, src/Map.js, src/ToggleBar.js
Fixes #7 (add traffic layer toggle)
=> Add a traffic layer toggle

dune-buggy.js
Refactor log query logic slightly.  Still more to
be done once tasks are supported.
Fixes #11
=> feat: Support lookup by trip instead of just vehicle

.eslintignore, .eslintrc.json, .github/workflows/ci.yml, .github/workflows/docs.yml, components/browser.js, package-lock.json, package.json, src/LogTable.js, src/Map.js, src/ToggleBar.js, src/index.js
Attempt to address mismatch between eslint configs
used by 'npm start' (react scripts) and 'npm run lint'.
Fixes #29
=> fix: linting issues

src/App.test.js
... by disabling tests for now.   Filed issue to track
actually implementing tests.   Tests are failing due to missing generated datafile.
=> "Fix" npm test

dune-buggy.js, src/App.js
Allows the map to be visible when scrolling down the long logs.
Fixes #43
=> fix: logviewer component scrolls on overflow

src/App.js, src/Map.js, src/ToggleBar.js
Still needs a lot of work.  But it's at least minimally functional.
See comments in code for all the issues
Fixes #35
=> feat: add rudimentary dwell time visualization

src/Map.js
Doesn't attempt to support more generic url parameters or routing.
=> feat: Allow apikey to be specified as url parameter

.github/blunderbuss.yml
Add blunderbuss.yml so pull requests and issues are auto-assigned.
=> ci: Add blunderbuss.yml config

dune-buggy.js
It's not necessary in the historical view
Fixes #58
=> fix: Only bake in jwt & project id when using live mode

src/App.js, src/Map.js, src/ToggleBar.js, src/index.js, src/vehicleData.js
Error handling/expired tokens will be addressed in a future checkin.
Currently only supports one of the 3 location providers (ride sharing vehicle
tracking).
Fixes #20
=> feat: Add 'live view' toggle

.prettierignore, dune-buggy.js, src/Map.js, src/index.js, src/vehicleData.js
Changes:
- Refactored slightly how logs are gathered.
- Doesn't forec use to indicate whether vehicle being
debugged is a delivery or ridesharing vehicle
- very basic plumbing on the visualization to get the route
path
- haven't yet updated the log viewer or other components
Fixes #6
=> feat:Add very basic LMFS support to the debugger

docs/MissingUpdates.md, docs/VelocityJumps.md, src/ToggleBar.js
Also added placeholder doc pages for jump visualizations
Fix: #80
=> fix: add links to documentation for the visualizations

src/TripLogs.js, src/TripLogs.test.js, src/vehicleData.js
Adds the simplest possible test.  Future changes should now start adding tests.
Fixes #38
=> fix: adds first regression test

src/App.js, src/Map.js, src/ToggleBar.js
Fixes #77 
Radius of the bubble is equal to the timedelta in seconds
=> feat: Visualize client server time deltas

package-lock.json, package.json, src/App.js, src/Map.js, src/ToggleBar.js, src/queryString.js
With this change the state of the visualizations as well
as the map zoom and time range will be saved & restored from
the url.  Links now work as expected!
Fixes #86
=> fix: add support saving/restoring state from the url

src/App.js, src/Map.js
adds bubbles colored by trip status.  Kind of hard
to read ... but better than nothing
Fixes #<issue_number_goes_here>
> It's a good idea to open an issue first for discussion.
=> feat: add trip status visualization

src/App.js, src/Map.js, src/TripLogs.js
Fixes #<issue_number_goes_here>
> It's a good idea to open an issue first for discussion.
=> feat: add eta vsa ata visualizations

src/App.js, src/HighVelocityJump.js, src/LogTable.js, src/Map.js, src/MissingUpdate.js, src/TripLogs.js, src/vehicleData.js
Changes:
- allow toggle buttons & table columns to be customized
based on solution type
- simplify/hide implementation details by copying
common fields (ie lastLocation) into a standard
location.
- Add basic remaining tasks, distance & segment columns
for LMFS
=> feat: improve lmfs support

dune-buggy.js, src/Map.js, src/index.js, src/vehicleData.js
The mapId can either be passed as a url parameter
(mapId=<...>) or via the dune-buggy.js script with the --mapId=<...>
option.
=> feat: support mapId in fleet debugger

components/datasource.js, dune-buggy.js
Prep work for supporting bigquery as a log source in addition
to just cloud logging. No functional changes in this change
This change indirects all access to log data via a generic
'Datasource' class.
Fixes #108
=> feat: refactor logging access code

src/Map.js
This allows users to select satellite imagery
=> feat: enable mapTypeControl

components/cloudLoggingDS.js
This file got lost in a rename, and broke the dune-buggy script
Fixes #<issue_number_goes_here>
> It's a good idea to open an issue first for discussion.
=> fix: add missing file

src/Map.js
Being able to see the buildings provides some context.  Note
that the polygons don't get occluded by the 3d buildings -- to
do that we'd need to switch to & enable a webgl overlay.
=> feat: Add tilt & streetview controls

src/vehicleData.js
This allows a single fleet-debugger app to render multiple files.
=> feat: allow a single build react app to render multiple json files

.gitignore, cloud-run/README.md, cloud-run/deploy.sh, cloud-run/fleet-debugger.sh, cloud-run/package.json, components/serve.js, dune-buggy.js, src/ServeHome.js, src/index.js
Usage:
run:
npm run build
./dune-buggy.js serve --apikey
Then localhost:3000 will host a site where vehicles/trips
can be specified for debugging.
=> feat: Add support for cloud run

src/LogTable.js
Fixes #16 #24 
- Selected table will be highlighted
- Clicking on table header cell will sort the corresponding column
- Each column can be filtered by input string
Extra:
- Added pagination so UI doesn't slow down when number of entries is very large
=> add sort, filter, pagination and highlight selection to log table

dune-buggy.js
Add -- fleetachive to dune-buggy help
=> Add -- fleetachive to dune-buggy help

package-lock.json, package.json, src/App.js, src/HighVelocityJump.js, src/LogTable.js, src/Map.js, src/Task.js, src/TimeSlider.js, src/TripLogs.js, src/constants.js, src/global.css, src/index.js, src/localStorage.js, src/vehicleData.js
Fixes #17
Fixes #114
Fixes #133
I will be an active maintainer of this project going forward.
Revamp of Fleet-Debugger to be more focused on local storage importing of logs data.
Streamlined Log Export: Customers can easily export log files via Google Cloud Console's Cloud Logging UI.
Direct Log Upload: Users can upload log exports (in zip or JSON format) directly to Fleet Debugger.
Interactive Event Linking: Clicking an event simultaneously visualizes it on both the map and timeline for comprehensive analysis.
Responsive Design: Everything is client side. Keyboard shortcuts to rapidly step through the events.
Will update the manual/instructions in followup PR.
=> feat: Revamp (Local Storage, Event Linking, Layout, Error Highlights)

src/Map.js, src/PolylineCreation.js, src/global.css
Adds a small UI to add polylines based on a list of waypoints.
Useful when you want to compare routes taken. Projected route vs. actual route.
=> feat: Add Polyline tool.

src/localStorage.js, src/localStorage.test.js
=> fix: Handle Restrictedlogs for request.vehicle.currentRouteSegment

.prettierrc.json, src/Map.js, src/TripLogs.js
Not a lot of actual code changes, this includes a lot of small formatting changes due to the switch to 120 line length
=> feat: last known location, heading, traffic

src/App.js, src/App.test.js, src/Dataframe.js, src/HighVelocityJump.js, src/LogTable.js, src/MissingUpdate.js, src/PolylineCreation.js, src/ServeHome.js, src/Stats.js, src/Task.js, src/TaskLogs.js, src/TaskLogs.test.js, src/TimeSlider.js, src/ToggleBar.js, src/TrafficPolyline.js, src/TrafficPolyline.test.js, src/Trip.js, src/TripLogs.test.js, src/Utils.js, src/constants.js, src/global.css, src/index.js, src/localStorage.js, src/localStorage.test.js, src/queryString.js, src/setupTests.js, src/vehicleData.js
No code change, only lint prettier formatting
=> chore: prettier 120 characters formatting changes

src/App.js, src/TripLogs.js, src/global.css
+ fix: reset lastKnownState for planned route and traffic if NO_GUIDANCE
=> feat: map minimum height of 200px

package-lock.json, package.json, src/App.js, src/CloudLogging.js, src/CloudLogging.test.js, src/LogTable.js, src/PolylineCreation.js, src/ToggleBar.js, src/global.css, src/localStorage.js
Fixes #209
This is deployed to https://fleet-debugger.web.app
Other minor changes:
- Drop down on datasets to DELETE or SAVE. SAVE makes sense with Cloud Logging, it will enable users to quickly gather the logs to send to our Support.
- Datasets remember the last selected row, and when switching dataset, it would go back to the previous row selected.
=> feat: Direct Cloud logging using Google gsi client

src/App.js, src/Map.js, src/TimeSlider.js, src/TrafficPolyline.js, src/TripObjects.js, src/global.css
breaking change, does no longer filter time range via map or time slider clicks.
=> feat!: find events on timeslider or on map. follow vehicle button.

_includes/head-custom.html
=> chore:google-site-verification
