src/Map.js

Ideally we'd squash the map element down to 1/2 size and show the
streetview side-by-side.  My JS skills aren't up to the task
so for now, the entire map view is replaced.
Uses heading from the the logs so that the streetview is properly 
orientated to the direction the vehicle was traveling at that point.
Fixes #8

Popup streetview when heading arrows are click on

---

components/logging.js
dune-buggy.js
src/Map.js

CreateTrip logs aren't labeled by vehicle id (since vehicle hasn't
been assigned yet).  The 2nd pass log search was only bringing
the first trip.  Label based log lookup now supports arrays of values.
Also fixed sorting for trip related logs, and re-ran
npx prettier --write . to fix formatting.
Fixes #12

Properly extract all trips from the logs

---

src/Map.js

Use m/s as radius of speed bubbles.   Makes it very obvious
when speed is slower.  Color negative speed bubbles red.  I don't
know what a negative speed means (but it shows up in log data).
Fixes #32

fix: Make speed visualization more useful #32

---

dune-buggy.js

When a vehicle is on multiple trips the label in cloud logging
has all the trips in CSV.  Split those trips out to ensure logs
for all trips are gathered.  Future work to better visualize these
overlapping trips still needed.
Fixes #31

fix: minimal handling for overlapping trips #31

---

src/Map.js
src/index.js
src/vehicleData.js

api key was already getting forwarded via generated datafile --
it just wasn't getting used.
The exposed api key has already been deleted

fix: Remove baked in apikey

---

src/App.js
src/LogTable.js
src/Map.js
src/TimeSlider.js
src/Trip.js
src/TripLogs.js
src/index.js
src/vehicleData.js

This change refactors how trips our visualized:
- trips are now broken up into trip & not trip segments
- Added TripLogs and Trip classes
- Removed duplicated processing
- Fixed issues with dwellTimes not respecting the time slider
- Add trip status to the timeslider
- Addressed trip coloring
- Added highlight & click functionality to the trip polylines
- Updated last vehicle location to fancy image icon
- Removed start/end trip markers (not necessary with new
trip highlighting/click functionality)
- continued trend of very minimal LMFS support.  TripLogs
likely needs to be renamed 'VehicleLogs' and refactored into
Trip/Task components.   For now this at least gives visualization
where separate stops are colored separately
Addresses issues: …

feat: Process logs into logical trip segments

---

README.md

fix: Update demo links in readme to use googlemaps.github.io

fix: Update readme with proper links to github pages

---

src/Map.js
src/TripLogs.js

When visualizing jumps using the location in the
response will show spurious jumps in this case:
1) update vehicle  (location in field mask)
2) Long time gap (ie app crashes, offline, etc)
3) update vehicle (non-location properties in fieldmask)
4) update vehicle (location in field mask)
In step 3, the location in the response will be the location
from step 1 -- and thus very stale.

fix: use location from request, not response

---

src/App.js
src/HighVelocityJump.js
src/LogTable.js
src/Map.js
src/MissingUpdate.js
src/Stats.js
src/TimeSlider.js
src/ToggleBar.js
src/Trip.js
src/TripLogs.js
src/Utils.js
src/vehicleData.js

This change adds two different types of jump visualizations:
* high-velocity jumps: locations where between two updates
the calculated straight line speed of the vehicle exceeded a
reasonable speed.   Visualized as an arrow with click &
mouse over actions
* missing updates: places where no location updates were recevied.
This could be due to cell signal problems, device going offline,
etc.  Visualized as offset lines (like dimentions on an architectural
drawing) -- which seems to better show the temporal only jumps.
Click & mouseover actions are supported
Other changes include:
* expose ability to set the timeslider range
* click handlers for jumps & trips now focus timeslider
and log viewer onto the range in question
* cleanup some minDate/maxDate vars that were really time values
Fixes …

feat: visualize jumps

---

src/Map.js
src/TripLogs.js

With this change when you mouseover a dwell bubble the
json viewer will show the duration of the dwell time.
Fixes #64

fix: add mouseover information on dwell time bubbles

---

src/App.js
src/Map.js

Shows bubbles colored by current navigation status.   Very
first step towards showing deviations (since red 'off route' bubbles
likely indicate a deviation from the route).
Fixes #<issue_number_goes_here>
> It's a good idea to open an issue first for discussion.

feat: add navigation status visualization

---

dune-buggy.js

With this change the number of task_ids for which detailed task
logs are gathered is limited to 20 (arbitrarily) to prevent
limit exceeded errors on the cloud logging query string length.
A real fix is tracked in issue #100
Fixes #99

fix: limit number of tasks in cloud logging query

---

.gitignore
appengine/README.md
appengine/app.yaml
appengine/deploy.sh
appengine/fleet-debugger.sh
appengine/package.json

Allows fleet-debugger to be deployed to app-engine.   With this change fleet-debugger could run along side our sample apps.

Add app engine support

---

.github/workflows/release.yml
.github/workflows/test.yml

Ideally we would update the version for the dependency semantic-release in semantic-release-config to v20.

build: workflow versions to v19

---

src/localStorage.js

For customers with restricted logs enabled.
Vehicle logs as well as Trip logs.

feat: merge restricted logs into their parent log.

---

package-lock.json
package.json
src/Map.js
src/PolylineCreation.js
src/TrafficPolyline.js
src/TrafficPolyline.test.js
src/Utils.js
src/index.js

Fixes #61
A lot of work but finally done.
This shows the polylines from Navigation SDK when they are available via the restricted logs.
I will still add some more controls over it in follow up PRs.

feat: Polyline with Traffic and better debug control

---

datasets/two-trips-bay-area.json
src/TripLogs.js
src/localStorage.js

Fix Dataset, it was missing restricted CreateTrip.
Also process trip restricted attributes when loading raw logs.

fix: CreateTrip request restricted logs fields

---

src/App.js
src/Map.js
src/TrafficPolyline.js
src/Trip.js
src/TripLogs.js
src/TripObjects.js

feat: Add markers for pickup and dropoff for each trip

---

src/Dataframe.js
src/localStorage.js

Small Quality of Life change.
Easier to compare some data over multiple rows without adding the value to the table. Makes the page look less crowded by default.

feat: Sort JSON fields, and show JSON default mostly collapsed

---

.eslintrc.json
src/App.js
src/Map.js
src/TimeSlider.js
src/TrafficPolyline.js
src/Trip.js
src/TripLogs.js
src/TripLogs.test.js
src/TripObjects.js

Fixes #123
Also removing that the zooming would reset the tracking.
Still showing the rawLocation as a small red dot if it's not below the Chevron of the vehicle.

feat: visualize getTrip and use location instead of rawLocation

---

src/App.js
src/Trip.js
src/TripLogs.js
src/TripObjects.js
src/localStorage.js

Non Trips as grey polylines and more trip colors.

Feat: Prune logs to current selection.

---

src/App.js
src/Dataframe.js
src/Map.js
src/MapToggles.js
src/TripLogs.js
src/TripLogs.test.js

fix: restore Scheduled Task (LMFS) functionality

---

src/App.js

This PR fixes a race condition that caused a crash on Firefox when loading LMFS datasets. The fix ensures the `TaskLogs` object is properly initialized and managed, restoring LMFS map functionality on firefox.

fix: Resolve Firefox crash by ensuring TaskLogs is initialized
